Repository exercism/powershell, pull requests merged in 2023-07, with the labels that each got.

#197 [About.md]: Formatting changes
  docs/ABOUT.md
Labels: x:rep/small

#199 [Config.json]: Fix example file path
  config.json
Labels: x:rep/tiny

#205 [Resources.md]: Various fixes
  docs/RESOURCES.md
Labels: x:rep/small

#206 [Learning.md]: Various fixes
  docs/LEARNING.md
Labels: x:rep/small

#207 [Tests.md]: Improvments
  docs/TESTS.md
Labels: x:rep/small

#216 Convert `average_run_time` to an integer
  config.json
Labels: x:size/tiny

#226 Fix author
  exercises/practice/nth-prime/.meta/config.json
Labels: x:rep/tiny
