Repository exercism/powershell, pull requests merged in 2024-01, with the labels that each got.

#327 Sync fetch-configlet.ps1 script
  bin/fetch-configlet.ps1
Labels: x:size/tiny

#335 leap: sync
  exercises/practice/leap/.docs/introduction.md
Labels: x:size/tiny

#344 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny

#343 Update the test suite
  exercises/practice/acronym/.meta/Acronym.example.ps1
  exercises/practice/acronym/Acronym.tests.ps1
Labels: x:action/fix, x:rep/tiny

#345 Update no-important-files-changed.yml
  .github/workflows/no-important-files-changed.yml
Labels: x:type/ci, x:rep/tiny
